---
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest
trigger:
  - main

extends:
  template: ./templates/npm_reuse.yaml
  parameters:
    branch: 'main'
    agentvmImage: 'ubuntu-18.04'
    npmversion: '16.x'
    

