---
pool:
  name: "Azure Pipelines" 
  vmImage: 'ubuntu-latest'

trigger:
  - main


resources:
  repositories:
    - repository: 'azure_pipeline'
      name: 'nkishore555/azure_pipeline'
      endpoint: 'github.com_nkishore555'
      type: 'github'
      ref: 'refs/heads/main'

steps:
  - template: maven-reusable-template.yaml@azure_pipeline
    parameters:
      jdkVersion: '1.17'